# Generated by Django 2.1.5 on 2019-09-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_sysbutton_sysmenu_sysmenubutton_sysorg_sysorgrole_sysrole_sysrolebutton_sysrolemenu_sysroleparam_sys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sysuser',
            options={},
        ),
    ]
