# Generated by Django 2.1.5 on 2019-09-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_auto_20190918_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysuser',
            name='account',
        ),
        migrations.AddField(
            model_name='sysuser',
            name='username',
            field=models.CharField(db_column='USERNAME', default='xxx', max_length=50),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='name',
            field=models.CharField(db_column='NAME', max_length=100),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='password',
            field=models.CharField(db_column='PASSWORD', max_length=32),
        ),
    ]
