# Generated by Django 2.1.5 on 2019-09-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_auto_20190918_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='username',
            field=models.CharField(db_column='USERNAME', max_length=50),
        ),
    ]
