# Generated by Django 2.1.5 on 2019-09-19 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_auto_20190918_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysuser',
            name='agent_id',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='agent_last_login_time',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='agent_phone',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='agent_pwd',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='bearing_status',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='census_register_type',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='config_status',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='department_path',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='kids_born_date',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='marry_date',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='modify_password_lasttime',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='nation',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='native_place',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='night_account',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='oa_account',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='oa_account_status',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='platform_id',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='politics_status',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='role_type',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='submit_status',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='task_message_min',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='task_notice_min',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='user_icon',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='user_zw',
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='org_id',
            field=models.ForeignKey(blank=True, db_column='ORG_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='webpage.SysOrg'),
        ),
    ]
