# Generated by Django 2.1.5 on 2019-09-20 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_auto_20190919_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='email',
        ),
    ]
