# Generated by Django 2.1.5 on 2019-09-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0009_auto_20190920_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sysuser',
            old_name='username',
            new_name='account',
        ),
    ]
