# Generated by Django 2.1.5 on 2019-09-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_auto_20190920_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='account',
            field=models.CharField(db_column='ACCOUNT', max_length=50),
        ),
    ]
